{allChans: [1, 2, 3, 4, 5, 6, 7, 8, 19,20], 
apdChans: [1, 2, 3, 4], 
binWidth1: 1000, 
binWidth2: 1000,
counter_channels:[1,2,3,4],
binWidthCounter: 40000000000, 
binWidthScanCounter: 40000, 
currentChan1: [1],
currentChan2: [2], 
gatedChan:[4],
gate_delay:[2000, 30000],
g2_channels_start:[1,2],
g2_channels_end:[2,3],
dataChans: [1, 2, 3, 4, 5, 6, 7, 8, 9], 
dataDir: /fastdata/measurements,
delayTimes: [0, -11700, 2000, -5500, 0, 50000, 50000, 50_000, 50_000, 190000], 
maxDumps: 1000000000,
maxStream: 1000000000, 
numBins1: 1000, 
numBins2: 1000, 
numBinsCounter: 300, 
numBinsScanCounter: 300,
refreshTime1: 1, 
refreshTime2: 1, 
saveDir: /fastdata/measurements/test_cross_pol,
trigChans: [5, 6, 7, 8, 9], 
testSignals:[1,2,3,4,5]}
